title: Antonio Toto Castaldi
email: toto.castaldi@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://toto-castaldi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag